install:
  - choco install gitversion.portable -pre -y

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

build_script:
  - cmd: build.cmd

after_build:
  - cmd: appveyor PushArtifact "Build\Linq2OData.Client.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "Build\Linq2OData.Server.%GitVersion_NuGetVersion%.nupkg"
deploy:
- provider: NuGet
  server: https://www.myget.org/F/tocsoft/api/v2/package
  api_key:
    secure: SyrSERGrjkK21TSCsHtqke5279SMxXCg2NXKjR2qaErP0khEplwxPwE8Ch5bxzyf
  skip_symbols: true
  on:
    branch: master